kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: coffeeshop-service
  labels:
    app: coffeeshop-service
spec:
  host: coffeeshop-service-gd-gameday.apps.aws-innovate.bvir.p1.openshiftapps.com
  path: /
  to:
    kind: Service
    name: coffeeshop-service
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge