---
apiVersion: v1
kind: Service
metadata:
  name: coffeeshop-service
  labels:
    app:  coffeeshop-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app:  coffeeshop-service
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080