kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: coffeeshop-deploy
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "coffeeshop-deploy"
      server: "*"
  sourceRepos:
    - "*"
  roles:
    - description: AWS developer admin group
      groups:
        - awsdeveloper
      name: awsdeveloper
      policies:
        - >-
          p, proj:coffeeshop-kafka:awsdeveloper, applications, *,
          coffeeshop-kafka/*, allow
