---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: coffeeshop-kafka
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: coffeeshop-kafka
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: coffeeshop-kafka
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: '4.0'
      min.insync.replicas: 2
      num.partitions: {{ .Values.partition_count }}
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: {{ .Values.port.internal }}
        tls: false
        type: internal
      - name: tls
        port: {{ .Values.port.tls }}
        tls: true
        type: internal
    version: 4.0.0
  entityOperator:
    topicOperator: {}
    userOperator: {}
